
// Modificando Cantidad de Vuelos

CantidadVuelos = COUNTROWS(vuelo1)

// Modificando la cantidad de vuelos exitosos 

VuelosExitosos = COUNTROWS(FILTER(vuelo1, vuelo1[ID_EstadoVuelo] = "E"))

// Modificando porcentaje de vuelos exitosos 

PorcentajeExitosos = DIVIDE(vuelo1[VuelosExitosos],[CantidadVuelos])



// Cantidad de vuelos que salieron adelantados "A" y a tiempo "B"

VuelosAdelantados_D = COUNTROWS(FILTER(vuelo1, OR(vuelo1[ID_DepTime]="A",vuelo1[ID_DepTime]="B")))

// Cantidad de vuelos que arribaron adelantados "A" O a tiempo "B"

VuelosAdelantados_A = COUNTROWS(FILTER(vuelo1, OR(vuelo1[ID_ArrTime]="A",vuelo1[ID_ArrTime]="B")))

// Modificando porcentaje de vuelos que partieron a tiempo 

PorcentajeAdelantados_D = DIVIDE(vuelo1[VuelosAdelantados_D],[VuelosExitosos])

// Modificando porcentaje de vuelos que arribaron a tiempo 

PorcentajeAdelantados_A = DIVIDE(vuelo1[VuelosAdelantados_A],[VuelosExitosos])




// ############################################################################################


// Hallando una medida que muestre los minutos de retraso de los vuelos TiempoSalidaR - TiempoSalidaP

RetrasoSalida = SUMX(FILTER(vuelo1, vuelo1[ID_EstadoVuelo] = "E"), vuelo1[Hora_SalidaR] - vuelo1[Hora_SalidaP])